# Generated by Django 5.2.3 on 2025-06-20 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('temperatura', 'Temperatura'), ('umidade', 'Umidade'), ('luminosidade', 'Luminosidade'), ('contador', 'Contador de Pessoas')], max_length=20)),
                ('valor', models.CharField(max_length=50)),
                ('localizacao', models.CharField(max_length=100)),
                ('data_leitura', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
