# Generated by Django 5.1.7 on 2025-06-20 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='data_leitura',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Leitura'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='localizacao',
            field=models.CharField(max_length=100, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='tipo',
            field=models.CharField(choices=[('temperatura', 'Temperatura'), ('umidade', 'Umidade'), ('luminosidade', 'Luminosidade'), ('contador', 'Contador de Pessoas')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='valor',
            field=models.CharField(max_length=50, verbose_name='Valor'),
        ),
    ]
