# Generated by Django 5.2.6 on 2025-09-26 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ambiente_remove_sensor_data_leitura_sensor_ambiente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='data_leitura',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='ambiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensores', to='app.ambiente'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='localizacao',
            field=models.CharField(help_text='Ex: Praça Central, Pátio 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='tipo',
            field=models.CharField(choices=[('temperatura', 'Temperatura (°C)'), ('umidade', 'Umidade (%)'), ('luminosidade', 'Luminosidade (lux)'), ('contador', 'Contador de Pessoas')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='valor',
            field=models.FloatField(help_text='Valor atual do sensor'),
        ),
    ]
